from __future__ import annotations

from typing import Any


DEMO_PRESETS: dict[str, dict[str, Any]] = {
    "自定义": {},
    "均衡巡逻演示": {
        "uav_count": 8,
        "action_range": 5,
        "sim_steps": 120,
        "target_coverage_pct": 90,
        "coverage_mode_label": "累计覆盖率",
        "rolling_window": 14,
        "risk_strategy_label": "均衡权衡",
        "risk_failure_pct": 12,
        "random_seed": 20250711,
        "task_count": 3,
        "risk_count": 1,
        "task_r_0": 16,
        "task_c_0": 43,
        "task_rad_0": 6,
        "task_r_1": 43,
        "task_c_1": 43,
        "task_rad_1": 6,
        "task_r_2": 30,
        "task_c_2": 22,
        "task_rad_2": 6,
        "risk_r_0": 36,
        "risk_c_0": 34,
        "risk_rad_0": 12,
    },
    "滚动覆盖韧性": {
        "uav_count": 10,
        "action_range": 5,
        "sim_steps": 120,
        "target_coverage_pct": 88,
        "coverage_mode_label": "滚动覆盖率",
        "rolling_window": 14,
        "risk_strategy_label": "覆盖优先",
        "risk_failure_pct": 35,
        "random_seed": 20250712,
        "task_count": 3,
        "risk_count": 2,
        "task_r_0": 15,
        "task_c_0": 44,
        "task_rad_0": 7,
        "task_r_1": 44,
        "task_c_1": 44,
        "task_rad_1": 7,
        "task_r_2": 30,
        "task_c_2": 24,
        "task_rad_2": 6,
        "risk_r_0": 38,
        "risk_c_0": 37,
        "risk_rad_0": 15,
        "risk_r_1": 26,
        "risk_c_1": 31,
        "risk_rad_1": 9,
    },
    "长期无损策略转进": {
        "uav_count": 8,
        "action_range": 5,
        "sim_steps": 120,
        "target_coverage_pct": 92,
        "coverage_mode_label": "累计覆盖率",
        "rolling_window": 14,
        "risk_strategy_label": "安全优先",
        "risk_failure_pct": 0,
        "random_seed": 20250713,
        "task_count": 3,
        "risk_count": 1,
        "task_r_0": 17,
        "task_c_0": 45,
        "task_rad_0": 6,
        "task_r_1": 43,
        "task_c_1": 41,
        "task_rad_1": 7,
        "task_r_2": 31,
        "task_c_2": 23,
        "task_rad_2": 6,
        "risk_r_0": 38,
        "risk_c_0": 36,
        "risk_rad_0": 16,
    },
}
